import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import '@fontsource/manrope/latin.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <footer className="text-center py-8 text-sm text-gray-400 bg-sky-800/30">
        © 2025 Жорик. Сделано с заботой. <br className="hidden md:inline" />
        <div className="mt-2 space-x-4">
          <a href="https://t.me/joryk_bot" className="underline hover:text-white">Бот</a>
          <a href="https://github.com/devjutsu/joryk-landing" className="underline hover:text-white">GitHub</a>
          <a href="https://t.me/devjutsu" className="underline hover:text-white">@devjutsu</a>
        </div>
      </footer>
      </body>
    </html>
  );
}
